name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
        
    - name: Install dependencies
      run: |
        cd web
        npm ci
        
    - name: Build application
      run: |
        cd web
        npm run build
        
    - name: Create deployment structure
      run: |
        echo "Creating public_html structure..."
        mkdir -p deploy/public_html
        cp -r web/dist/* deploy/public_html/
        echo "Files in deploy/public_html/:"
        ls -la deploy/public_html/
        echo "Files in deploy/public_html/assets/:"
        ls -la deploy/public_html/assets/
        
    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: deploy/
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/.env.*
        include: |
          **/.htaccess
        log-level: verbose
        dry-run: false
